easy_admin:
  site_name: 'Far &amp; Beyond'
  list:
    actions:
      - { name: show, css_class: 'btn btn-xs btn-default', icon: eye, label:  }
      - { name: edit, css_class: 'btn btn-xs btn-default', icon: edit, label:  }
      - { name: delete, css_class: 'btn btn-xs btn-danger', icon: trash-o, label:  }

  design:
    brand_color: '#1ABC9C'
    form_theme: vertical
    templates:
      edit: 'filechooser/edit.html.twig'
      new: 'filechooser/new.html.twig'
    assets:
      css:
        - 'https://localhost:8080/build/editor.css'
        - '/filechooser/css/style.css'
      js:
        - 'https://localhost:8080/build/manifest.js'
        - 'https://localhost:8080/build/vendor.js'
        - 'https://localhost:8080/build/admin.js'
        - '/filechooser/js/picker.js'

    menu:
      - { entity: Project, icon: wordpress }

  formats:
    date: d/m/Y
    time: 'H:i'
    datetime: 'd/m/Y H:i:s'

imports:
  - resource: easyadmin/project.yaml
